version: '3'

services:
    
###### Kafka+Zookeeper Cluster

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka-1:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
####### Connect Cluster
  
  connect-1:
    image: confluentinc/cp-kafka-connect:latest
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-1:9092
      CONNECT_GROUP_ID: 1
      CONNECT_CONFIG_STORAGE_TOPIC: config
      CONNECT_OFFSET_STORAGE_TOPIC: offset
      CONNECT_STATUS_STORAGE_TOPIC: status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: volt-test-1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_REST_PORT: 28083
    ports:
      - "8083"
      - "9092"
      - "28083"
    volumes:
      - /Users/seetasomagani/Projects/kafka-connect-demo/config:/config
      - /Users/seetasomagani/Projects/kafka-connect-demo/data:/data
      - /Users/seetasomagani/distributions/kafka_2.12-2.5.0/plugins:/plugins

  connect-2:
    image: confluentinc/cp-kafka-connect:latest
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-1:9092
      CONNECT_GROUP_ID: 2
      CONNECT_CONFIG_STORAGE_TOPIC: config
      CONNECT_OFFSET_STORAGE_TOPIC: offset
      CONNECT_STATUS_STORAGE_TOPIC: status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: volt-test-2
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_REST_PORT: 28083
    ports:
      - "8083"
      - "9092"
      - "28083"
    volumes:
      - /Users/seetasomagani/Projects/kafka-connect-demo/config:/config
      - /Users/seetasomagani/Projects/kafka-connect-demo/data:/data
      - /Users/seetasomagani/distributions/kafka_2.12-2.5.0/plugins:/plugins
####### MySQL Node
  
#  mysql-1:
#    image: mysql:latest
    